# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class InlineResponse20012Cars(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, location: Location = None):  # noqa: E501
        """InlineResponse20012Cars - a model defined in Swagger

        :param location: The location of this InlineResponse20012Cars.  # noqa: E501
        :type location: Location
        """
        self.swagger_types = {
            'location': Location
        }

        self.attribute_map = {
            'location': 'location'
        }
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20012Cars':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_12_cars of this InlineResponse20012Cars.  # noqa: E501
        :rtype: InlineResponse20012Cars
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self) -> Location:
        """Gets the location of this InlineResponse20012Cars.


        :return: The location of this InlineResponse20012Cars.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location: Location):
        """Sets the location of this InlineResponse20012Cars.


        :param location: The location of this InlineResponse20012Cars.
        :type location: Location
        """

        self._location = location
