# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reservation import Reservation  # noqa: F401,E501
from swagger_server import util


class InlineResponse2009(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, reservations: List[Reservation] = None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger

        :param reservations: The reservations of this InlineResponse2009.  # noqa: E501
        :type reservations: List[Reservation]
        """
        self.swagger_types = {
            'reservations': List[Reservation]
        }

        self.attribute_map = {
            'reservations': 'reservations'
        }
        self._reservations = reservations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2009':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_9 of this InlineResponse2009.  # noqa: E501
        :rtype: InlineResponse2009
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reservations(self) -> List[Reservation]:
        """Gets the reservations of this InlineResponse2009.


        :return: The reservations of this InlineResponse2009.
        :rtype: List[Reservation]
        """
        return self._reservations

    @reservations.setter
    def reservations(self, reservations: List[Reservation]):
        """Sets the reservations of this InlineResponse2009.


        :param reservations: The reservations of this InlineResponse2009.
        :type reservations: List[Reservation]
        """

        self._reservations = reservations
