# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.all_oflocation_id_body_patch import AllOflocationIdBodyPatch  # noqa: F401,E501
from swagger_server import util


class LocationIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, patch: AllOflocationIdBodyPatch = None):  # noqa: E501
        """LocationIdBody - a model defined in Swagger

        :param patch: The patch of this LocationIdBody.  # noqa: E501
        :type patch: AllOflocationIdBodyPatch
        """
        self.swagger_types = {
            'patch': AllOflocationIdBodyPatch
        }

        self.attribute_map = {
            'patch': 'patch'
        }
        self._patch = patch

    @classmethod
    def from_dict(cls, dikt) -> 'LocationIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The location_id_body of this LocationIdBody.  # noqa: E501
        :rtype: LocationIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def patch(self) -> AllOflocationIdBodyPatch:
        """Gets the patch of this LocationIdBody.

        Co zmienic? Tylko te wartosci, ktore chcesz zmienic (oczywiskie niektorych rzeczy sie nie da, np modyfikowanie ID)  # noqa: E501

        :return: The patch of this LocationIdBody.
        :rtype: AllOflocationIdBodyPatch
        """
        return self._patch

    @patch.setter
    def patch(self, patch: AllOflocationIdBodyPatch):
        """Sets the patch of this LocationIdBody.

        Co zmienic? Tylko te wartosci, ktore chcesz zmienic (oczywiskie niektorych rzeczy sie nie da, np modyfikowanie ID)  # noqa: E501

        :param patch: The patch of this LocationIdBody.
        :type patch: AllOflocationIdBodyPatch
        """

        self._patch = patch
