# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RentRentBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, car_id: int = None, cvv: int = None, payment_type: str = None):  # noqa: E501
        """RentRentBody - a model defined in Swagger

        :param car_id: The car_id of this RentRentBody.  # noqa: E501
        :type car_id: int
        :param cvv: The cvv of this RentRentBody.  # noqa: E501
        :type cvv: int
        :param payment_type: The payment_type of this RentRentBody.  # noqa: E501
        :type payment_type: str
        """
        self.swagger_types = {
            'car_id': int,
            'cvv': int,
            'payment_type': str
        }

        self.attribute_map = {
            'car_id': 'carId',
            'cvv': 'cvv',
            'payment_type': 'paymentType'
        }
        self._car_id = car_id
        self._cvv = cvv
        self._payment_type = payment_type

    @classmethod
    def from_dict(cls, dikt) -> 'RentRentBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rent_rent_body of this RentRentBody.  # noqa: E501
        :rtype: RentRentBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def car_id(self) -> int:
        """Gets the car_id of this RentRentBody.

        id auta  # noqa: E501

        :return: The car_id of this RentRentBody.
        :rtype: int
        """
        return self._car_id

    @car_id.setter
    def car_id(self, car_id: int):
        """Sets the car_id of this RentRentBody.

        id auta  # noqa: E501

        :param car_id: The car_id of this RentRentBody.
        :type car_id: int
        """

        self._car_id = car_id

    @property
    def cvv(self) -> int:
        """Gets the cvv of this RentRentBody.

        Opcjonalnie: CVV karty do obciążenia  # noqa: E501

        :return: The cvv of this RentRentBody.
        :rtype: int
        """
        return self._cvv

    @cvv.setter
    def cvv(self, cvv: int):
        """Sets the cvv of this RentRentBody.

        Opcjonalnie: CVV karty do obciążenia  # noqa: E501

        :param cvv: The cvv of this RentRentBody.
        :type cvv: int
        """

        self._cvv = cvv

    @property
    def payment_type(self) -> str:
        """Gets the payment_type of this RentRentBody.

        Rodzaj platnosci. PP - prepaid, id karty - karta  # noqa: E501

        :return: The payment_type of this RentRentBody.
        :rtype: str
        """
        return self._payment_type

    @payment_type.setter
    def payment_type(self, payment_type: str):
        """Sets the payment_type of this RentRentBody.

        Rodzaj platnosci. PP - prepaid, id karty - karta  # noqa: E501

        :param payment_type: The payment_type of this RentRentBody.
        :type payment_type: str
        """

        self._payment_type = payment_type
