# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.all_ofuser_id_body_patch import AllOfuserIdBodyPatch  # noqa: F401,E501
from swagger_server import util


class UserIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, patch: AllOfuserIdBodyPatch = None):  # noqa: E501
        """UserIdBody - a model defined in Swagger

        :param patch: The patch of this UserIdBody.  # noqa: E501
        :type patch: AllOfuserIdBodyPatch
        """
        self.swagger_types = {
            'patch': AllOfuserIdBodyPatch
        }

        self.attribute_map = {
            'patch': 'patch'
        }
        self._patch = patch

    @classmethod
    def from_dict(cls, dikt) -> 'UserIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_id_body of this UserIdBody.  # noqa: E501
        :rtype: UserIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def patch(self) -> AllOfuserIdBodyPatch:
        """Gets the patch of this UserIdBody.

        Co zmienic? Tylko te wartosci, ktore chcesz zmienic (oczywiskie niektorych rzeczy sie nie da, np modyfikowanie ID)  # noqa: E501

        :return: The patch of this UserIdBody.
        :rtype: AllOfuserIdBodyPatch
        """
        return self._patch

    @patch.setter
    def patch(self, patch: AllOfuserIdBodyPatch):
        """Sets the patch of this UserIdBody.

        Co zmienic? Tylko te wartosci, ktore chcesz zmienic (oczywiskie niektorych rzeczy sie nie da, np modyfikowanie ID)  # noqa: E501

        :param patch: The patch of this UserIdBody.
        :type patch: AllOfuserIdBodyPatch
        """

        self._patch = patch
