//class User:
//     """NOTE: This class is auto generated by the swagger code generator program.
//
//     Do not edit the class manually.
//     """
//
//     def __init__(self, userId: str = None, login: str = None, password: str = None, email: str = None, name: str = None,
//                  surname: str = None,
//                  account_type: str = None, status: str = None, balance: str = None, pesel: str = None,
//                  driver_licence_number: str = None, driver_licence_expiration_date: str = None,
//                  last_rental: int = None, current_reservation: int = None, role: str = None,
//                  current_rental: Rental = None, cards: list = None, activationCode=None,
//                  rental_history_ids: list[str] = None):  # noqa: E501
//         """User - a model defined in Swagger
//
//         :param login: The login of this User.  # noqa: E501
//         :type login: str
//         :param email: The email of this User.  # noqa: E501
//         :type email: str
//         :param name: The name of this User.  # noqa: E501
//         :type name: str
//         :param surname: The surname of this User.  # noqa: E501
//         :type surname: str
//         :param account_type: The account_type of this User.  # noqa: E501
//         :type account_type: str
//         :param status: The status of this User.  # noqa: E501
//         :type status: str
//         :param balance: The balance of this User.  # noqa: E501
//         :type balance: str
//         :param pesel: The pesel of this UserDetails.  # noqa: E501
//         :type pesel: str
//         :param driver_licence_number: The driver_licence_number of this UserDetails.  # noqa: E501
//         :type driver_licence_number: str
//         :param driver_licence_expiration_date: The driver_licence_expiration_date of this UserDetails.  # noqa: E501
//         :type driver_licence_expiration_date: str
//         :param last_rental: The last_rental of this UserDetails.  # noqa: E501
//         :type last_rental: int
//         :param current_reservation: The last_reservation of this UserDetails.  # noqa: E501
//         :type current_reservation: int
//         :param role: The role of this UserDetails.  # noqa: E501
//         :type role: str
//         """
//
//         self._id = userId
//         self.login = login
//         self.password = password
//         self.email = email
//         self.name = name
//         self.surname = surname
//         self.accountType = account_type
//         self.status = status
//         self.balance = balance
//         self.pesel = pesel
//         self.driverLicenceNumber = driver_licence_number
//         self.driverLicenceExpirationDate = driver_licence_expiration_date
//         self.rentalHistoryIds = rental_history_ids
//         self.currentRental = current_rental
//         self.currentReservation = current_reservation
//         self.role = role
//         self.cards = cards
//         self.activationCode = activationCode
//
//     @classmethod
//     def from_dict(cls, dikt) -> 'User':
//         """Returns the dict as a model
//
//         :param dikt: A dict.
//         :type: dict
//         :return: The User of this User.  # noqa: E501
//         :rtype: User
//         """
//         u = User()
//         u.__dict__.update(dikt)
//         return u


class User{
    constructor(userId = "", login = "",  email  = "", name = "", surname = "", account_type = "",
                status = "", balance = "",  last_rental = 0, current_reservation = 0, role = "", current_rental_id= 0, cards = []) {
        this.userId = userId
        this.login = login
        this.email = email
        this.name = name
        this.surname = surname
        this.account_type = account_type
        this.status = status
        this.balance = balance

    }
}
