"""Removed esimnumber and countrycode

Revision ID: 7359bae6d15d
Revises: b6162b99d6ce
Create Date: 2022-02-01 22:19:39.457018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7359bae6d15d'
down_revision = 'b6162b99d6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cars', 'regCountryCode')
    op.drop_column('Cars', 'esimNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('esimNumber', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Cars', sa.Column('regCountryCode', mysql.VARCHAR(length=2), nullable=False))
    # ### end Alembic commands ###
