"""Removed addresses

Revision ID: b6162b99d6ce
Revises: e3b5b18317fd
Create Date: 2022-02-01 21:45:56.069900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6162b99d6ce'
down_revision = 'e3b5b18317fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'address')
    op.drop_column('CreditCards', 'cardHolderAddress')
    op.drop_column('Locations', 'locationAddress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Locations', sa.Column('locationAddress', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('CreditCards', sa.Column('cardHolderAddress', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('Clients', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
