"""Removed DriverLicense expiration date, changed Driver Licence number to string to account for potential non-numerical licences f.e. international

Revision ID: d39d0345c046
Revises: dade262f6d39
Create Date: 2022-02-01 20:47:20.872572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd39d0345c046'
down_revision = 'dade262f6d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clients', 'driverLicenceNumber',
                    existing_type=mysql.VARCHAR(30),
                    type=mysql.INTEGER(),
                    nullable=True)
    op.drop_column('Clients', 'driverLicenceExpirationDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients',
                  sa.Column('driverLicenceExpirationDate', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('Clients', 'driverLicenceNumber',
                    type=mysql.VARCHAR(30),
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
