# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GPSLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, location_lat: str = None, location_long: str = None):  # noqa: E501
        """GPSLocation - a model defined in Swagger

        :param location_lat: The location_lat of this GPSLocation.  # noqa: E501
        :type location_lat: str
        :param location_long: The location_long of this GPSLocation.  # noqa: E501
        :type location_long: str
        """
        self.swagger_types = {
            'location_lat': str,
            'location_long': str
        }

        self.attribute_map = {
            'location_lat': 'locationLat',
            'location_long': 'locationLong'
        }
        self._location_lat = location_lat
        self._location_long = location_long

    @classmethod
    def from_dict(cls, dikt) -> 'GPSLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GPSLocation of this GPSLocation.  # noqa: E501
        :rtype: GPSLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location_lat(self) -> str:
        """Gets the location_lat of this GPSLocation.

        Szerokosc geograficzna  # noqa: E501

        :return: The location_lat of this GPSLocation.
        :rtype: str
        """
        return self._location_lat

    @location_lat.setter
    def location_lat(self, location_lat: str):
        """Sets the location_lat of this GPSLocation.

        Szerokosc geograficzna  # noqa: E501

        :param location_lat: The location_lat of this GPSLocation.
        :type location_lat: str
        """

        self._location_lat = location_lat

    @property
    def location_long(self) -> str:
        """Gets the location_long of this GPSLocation.

        Dlugosc geograficzna  # noqa: E501

        :return: The location_long of this GPSLocation.
        :rtype: str
        """
        return self._location_long

    @location_long.setter
    def location_long(self, location_long: str):
        """Sets the location_long of this GPSLocation.

        Dlugosc geograficzna  # noqa: E501

        :param location_long: The location_long of this GPSLocation.
        :type location_long: str
        """

        self._location_long = location_long
