# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse4004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: int = None):  # noqa: E501
        """InlineResponse4004 - a model defined in Swagger

        :param error: The error of this InlineResponse4004.  # noqa: E501
        :type error: int
        """
        self.swagger_types = {
            'error': int
        }

        self.attribute_map = {
            'error': 'error'
        }
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse4004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400_4 of this InlineResponse4004.  # noqa: E501
        :rtype: InlineResponse4004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> int:
        """Gets the error of this InlineResponse4004.

        Blad w konczeniu rezerwacji! 1 - rezerwacja nie istnieje, 2 - rezerwacja juz zakonczona, 3 - nieznany blad  # noqa: E501

        :return: The error of this InlineResponse4004.
        :rtype: int
        """
        return self._error

    @error.setter
    def error(self, error: int):
        """Sets the error of this InlineResponse4004.

        Blad w konczeniu rezerwacji! 1 - rezerwacja nie istnieje, 2 - rezerwacja juz zakonczona, 3 - nieznany blad  # noqa: E501

        :param error: The error of this InlineResponse4004.
        :type error: int
        """

        self._error = error
