# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, car_id: int = None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param car_id: The car_id of this InlineResponse2006.  # noqa: E501
        :type car_id: int
        """
        self.swagger_types = {
            'car_id': int
        }

        self.attribute_map = {
            'car_id': 'carId'
        }
        self._car_id = car_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def car_id(self) -> int:
        """Gets the car_id of this InlineResponse2006.

        Id of a new added car  # noqa: E501

        :return: The car_id of this InlineResponse2006.
        :rtype: int
        """
        return self._car_id

    @car_id.setter
    def car_id(self, car_id: int):
        """Sets the car_id of this InlineResponse2006.

        Id of a new added car  # noqa: E501

        :param car_id: The car_id of this InlineResponse2006.
        :type car_id: int
        """

        self._car_id = car_id
