# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server.models.user_details import UserDetails  # noqa: F401,E501
from swagger_server import util


class InlineResponse20010Cars(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, car: User = None, details: UserDetails = None):  # noqa: E501
        """InlineResponse20010Cars - a model defined in Swagger

        :param car: The car of this InlineResponse20010Cars.  # noqa: E501
        :type car: User
        :param details: The details of this InlineResponse20010Cars.  # noqa: E501
        :type details: UserDetails
        """
        self.swagger_types = {
            'car': User,
            'details': UserDetails
        }

        self.attribute_map = {
            'car': 'car',
            'details': 'details'
        }
        self._car = car
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010Cars':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10_cars of this InlineResponse20010Cars.  # noqa: E501
        :rtype: InlineResponse20010Cars
        """
        return util.deserialize_model(dikt, cls)

    @property
    def car(self) -> User:
        """Gets the car of this InlineResponse20010Cars.


        :return: The car of this InlineResponse20010Cars.
        :rtype: User
        """
        return self._car

    @car.setter
    def car(self, car: User):
        """Sets the car of this InlineResponse20010Cars.


        :param car: The car of this InlineResponse20010Cars.
        :type car: User
        """

        self._car = car

    @property
    def details(self) -> UserDetails:
        """Gets the details of this InlineResponse20010Cars.


        :return: The details of this InlineResponse20010Cars.
        :rtype: UserDetails
        """
        return self._details

    @details.setter
    def details(self, details: UserDetails):
        """Sets the details of this InlineResponse20010Cars.


        :param details: The details of this InlineResponse20010Cars.
        :type details: UserDetails
        """

        self._details = details
