# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.car import Car  # noqa: F401,E501
from swagger_server.models.car_details import CarDetails  # noqa: F401,E501
from swagger_server import util


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, car: Car = None, details: CarDetails = None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param car: The car of this InlineResponse2007.  # noqa: E501
        :type car: Car
        :param details: The details of this InlineResponse2007.  # noqa: E501
        :type details: CarDetails
        """
        self.swagger_types = {
            'car': Car,
            'details': CarDetails
        }

        self.attribute_map = {
            'car': 'car',
            'details': 'details'
        }
        self._car = car
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def car(self) -> Car:
        """Gets the car of this InlineResponse2007.


        :return: The car of this InlineResponse2007.
        :rtype: Car
        """
        return self._car

    @car.setter
    def car(self, car: Car):
        """Sets the car of this InlineResponse2007.


        :param car: The car of this InlineResponse2007.
        :type car: Car
        """

        self._car = car

    @property
    def details(self) -> CarDetails:
        """Gets the details of this InlineResponse2007.


        :return: The details of this InlineResponse2007.
        :rtype: CarDetails
        """
        return self._details

    @details.setter
    def details(self, details: CarDetails):
        """Sets the details of this InlineResponse2007.


        :param details: The details of this InlineResponse2007.
        :type details: CarDetails
        """

        self._details = details
