# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2007 import InlineResponse2007  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cars: List[InlineResponse2007] = None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param cars: The cars of this InlineResponse2005.  # noqa: E501
        :type cars: List[InlineResponse2007]
        """
        self.swagger_types = {
            'cars': List[InlineResponse2007]
        }

        self.attribute_map = {
            'cars': 'cars'
        }
        self._cars = cars

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cars(self) -> List[InlineResponse2007]:
        """Gets the cars of this InlineResponse2005.


        :return: The cars of this InlineResponse2005.
        :rtype: List[InlineResponse2007]
        """
        return self._cars

    @cars.setter
    def cars(self, cars: List[InlineResponse2007]):
        """Sets the cars of this InlineResponse2005.


        :param cars: The cars of this InlineResponse2005.
        :type cars: List[InlineResponse2007]
        """

        self._cars = cars
