# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server.models.user_details import UserDetails  # noqa: F401,E501
from swagger_server import util


class InlineResponse20011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: User = None, details: UserDetails = None):  # noqa: E501
        """InlineResponse20011 - a model defined in Swagger

        :param user: The user of this InlineResponse20011.  # noqa: E501
        :type user: User
        :param details: The details of this InlineResponse20011.  # noqa: E501
        :type details: UserDetails
        """
        self.swagger_types = {
            'user': User,
            'details': UserDetails
        }

        self.attribute_map = {
            'user': 'user',
            'details': 'details'
        }
        self._user = user
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_11 of this InlineResponse20011.  # noqa: E501
        :rtype: InlineResponse20011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this InlineResponse20011.


        :return: The user of this InlineResponse20011.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this InlineResponse20011.


        :param user: The user of this InlineResponse20011.
        :type user: User
        """

        self._user = user

    @property
    def details(self) -> UserDetails:
        """Gets the details of this InlineResponse20011.


        :return: The details of this InlineResponse20011.
        :rtype: UserDetails
        """
        return self._details

    @details.setter
    def details(self, details: UserDetails):
        """Sets the details of this InlineResponse20011.


        :param details: The details of this InlineResponse20011.
        :type details: UserDetails
        """

        self._details = details
