# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Reservation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, reservation_id: int = None, reservation_start: int = None, duration: int = None,
                 card_id: int = None):  # noqa: E501
        """Reservation - a model defined in Swagger

        :param reservation_id: The reservation_id of this Reservation.  # noqa: E501
        :type reservation_id: int
        :param reservation_start: The reservation_start of this Reservation.  # noqa: E501
        :type reservation_start: int
        :param duration: The duration of this Reservation.  # noqa: E501
        :type duration: int
        :param card_id: The card_id of this Reservation.  # noqa: E501
        :type card_id: int
        """
        self.swagger_types = {
            'reservation_id': int,
            'reservation_start': int,
            'duration': int,
            'card_id': int
        }

        self.attribute_map = {
            'reservation_id': 'reservationId',
            'reservation_start': 'reservationStart',
            'duration': 'duration',
            'card_id': 'cardId'
        }
        self._reservation_id = reservation_id
        self._reservation_start = reservation_start
        self._duration = duration
        self._card_id = card_id

    @classmethod
    def from_dict(cls, dikt) -> 'Reservation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reservation of this Reservation.  # noqa: E501
        :rtype: Reservation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reservation_id(self) -> int:
        """Gets the reservation_id of this Reservation.

        Id rezerwacji  # noqa: E501

        :return: The reservation_id of this Reservation.
        :rtype: int
        """
        return self._reservation_id

    @reservation_id.setter
    def reservation_id(self, reservation_id: int):
        """Sets the reservation_id of this Reservation.

        Id rezerwacji  # noqa: E501

        :param reservation_id: The reservation_id of this Reservation.
        :type reservation_id: int
        """

        self._reservation_id = reservation_id

    @property
    def reservation_start(self) -> int:
        """Gets the reservation_start of this Reservation.

        Poczatek rezerwacji w unix time  # noqa: E501

        :return: The reservation_start of this Reservation.
        :rtype: int
        """
        return self._reservation_start

    @reservation_start.setter
    def reservation_start(self, reservation_start: int):
        """Sets the reservation_start of this Reservation.

        Poczatek rezerwacji w unix time  # noqa: E501

        :param reservation_start: The reservation_start of this Reservation.
        :type reservation_start: int
        """

        self._reservation_start = reservation_start

    @property
    def duration(self) -> int:
        """Gets the duration of this Reservation.

        Jak dlugo juz jest wypozyczony/byl wypozyczony?  # noqa: E501

        :return: The duration of this Reservation.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this Reservation.

        Jak dlugo juz jest wypozyczony/byl wypozyczony?  # noqa: E501

        :param duration: The duration of this Reservation.
        :type duration: int
        """

        self._duration = duration

    @property
    def card_id(self) -> int:
        """Gets the card_id of this Reservation.

        Zarezerwowane auto  # noqa: E501

        :return: The card_id of this Reservation.
        :rtype: int
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id: int):
        """Sets the card_id of this Reservation.

        Zarezerwowane auto  # noqa: E501

        :param card_id: The card_id of this Reservation.
        :type card_id: int
        """

        self._card_id = card_id
