# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserCardsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, card_number: int = None, expiration_date: str = None, card_holder: str = None, cvv: int = None,
                 holder_address: str = None):  # noqa: E501
        """UserCardsBody - a model defined in Swagger

        :param card_number: The card_number of this UserCardsBody.  # noqa: E501
        :type card_number: int
        :param expiration_date: The expiration_date of this UserCardsBody.  # noqa: E501
        :type expiration_date: str
        :param card_holder: The card_holder of this UserCardsBody.  # noqa: E501
        :type card_holder: str
        :param cvv: The cvv of this UserCardsBody.  # noqa: E501
        :type cvv: int
        :param holder_address: The holder_address of this UserCardsBody.  # noqa: E501
        :type holder_address: str
        """
        self.swagger_types = {
            'card_number': int,
            'expiration_date': str,
            'card_holder': str,
            'cvv': int,
            'holder_address': str
        }

        self.attribute_map = {
            'card_number': 'cardNumber',
            'expiration_date': 'expirationDate',
            'card_holder': 'cardHolder',
            'cvv': 'cvv',
            'holder_address': 'holderAddress'
        }
        self._card_number = card_number
        self._expiration_date = expiration_date
        self._card_holder = card_holder
        self._cvv = cvv
        self._holder_address = holder_address

    @classmethod
    def from_dict(cls, dikt) -> 'UserCardsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_cards_body of this UserCardsBody.  # noqa: E501
        :rtype: UserCardsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def card_number(self) -> int:
        """Gets the card_number of this UserCardsBody.

        CardNumber  # noqa: E501

        :return: The card_number of this UserCardsBody.
        :rtype: int
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number: int):
        """Sets the card_number of this UserCardsBody.

        CardNumber  # noqa: E501

        :param card_number: The card_number of this UserCardsBody.
        :type card_number: int
        """

        self._card_number = card_number

    @property
    def expiration_date(self) -> str:
        """Gets the expiration_date of this UserCardsBody.

        Data waznosci MM/YY  # noqa: E501

        :return: The expiration_date of this UserCardsBody.
        :rtype: str
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date: str):
        """Sets the expiration_date of this UserCardsBody.

        Data waznosci MM/YY  # noqa: E501

        :param expiration_date: The expiration_date of this UserCardsBody.
        :type expiration_date: str
        """

        self._expiration_date = expiration_date

    @property
    def card_holder(self) -> str:
        """Gets the card_holder of this UserCardsBody.

        Wlasciciel karty  # noqa: E501

        :return: The card_holder of this UserCardsBody.
        :rtype: str
        """
        return self._card_holder

    @card_holder.setter
    def card_holder(self, card_holder: str):
        """Sets the card_holder of this UserCardsBody.

        Wlasciciel karty  # noqa: E501

        :param card_holder: The card_holder of this UserCardsBody.
        :type card_holder: str
        """

        self._card_holder = card_holder

    @property
    def cvv(self) -> int:
        """Gets the cvv of this UserCardsBody.

        CVV karty  # noqa: E501

        :return: The cvv of this UserCardsBody.
        :rtype: int
        """
        return self._cvv

    @cvv.setter
    def cvv(self, cvv: int):
        """Sets the cvv of this UserCardsBody.

        CVV karty  # noqa: E501

        :param cvv: The cvv of this UserCardsBody.
        :type cvv: int
        """

        self._cvv = cvv

    @property
    def holder_address(self) -> str:
        """Gets the holder_address of this UserCardsBody.

        Adress wlasciciela karty  # noqa: E501

        :return: The holder_address of this UserCardsBody.
        :rtype: str
        """
        return self._holder_address

    @holder_address.setter
    def holder_address(self, holder_address: str):
        """Sets the holder_address of this UserCardsBody.

        Adress wlasciciela karty  # noqa: E501

        :param holder_address: The holder_address of this UserCardsBody.
        :type holder_address: str
        """

        self._holder_address = holder_address
